
CREATE TABLE `form_info` (
  `id` int(11) NOT NULL,
  `nombre` varchar(255) NOT NULL,
  `edad` int(11) DEFAULT NULL,
  `profesion` varchar(255) DEFAULT NULL,
  `correo` varchar(255) NOT NULL,
  `frecuencia` varchar(50) DEFAULT NULL,
  `actividades` text DEFAULT NULL,
  `importancia` tinyint(4) DEFAULT NULL,
  `acciones` text DEFAULT NULL,
  `voluntariado` varchar(50) DEFAULT NULL,
  `arboles` int(11) DEFAULT NULL,
  `horas` int(11) DEFAULT NULL,
  `areas` text DEFAULT NULL,
  `conocimiento` tinyint(4) DEFAULT NULL,
  `aprender` varchar(50) DEFAULT NULL,
  `informacion` varchar(50) DEFAULT NULL,
  `objetivos` text DEFAULT NULL,
  `cambios` text DEFAULT NULL,
  `mejorar` text DEFAULT NULL,
  `comentarios` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `form_info`
  ADD PRIMARY KEY (`id`);

INSERT INTO `form_info` (`id`, `nombre`, `edad`, `profesion`, `correo`, `frecuencia`, `actividades`, `importancia`, `acciones`, `voluntariado`, `arboles`, `horas`, `areas`, `conocimiento`, `aprender`, `informacion`, `objetivos`, `cambios`, `mejorar`, `comentarios`, `created_at`) VALUES
(1, 'Luis Alberto', 34, 'Biólogo', 'luis.alberto@example.com', 'diariamente', 'Investigación, observación de flora', 10, '[\"reciclaje\", \"productos_ecologicos\", \"plantacion\"]', 'si', 50, 100, '[\"conservacion_bosques\", \"proteccion_especies\"]', 9, 'si', 'si', 'Promover proyectos de investigación sobre biodiversidad local.', 'Implementar educación ambiental obligatoria.', 'Gestión de áreas protegidas.', 'La conservación debe ser prioridad en las políticas locales.', '2024-11-13 01:53:28'),
(2, 'María Fernanda', 28, 'Diseñadora de Interiores', 'maria.fernanda@example.com', 'semanalmente', 'Caminatas, diseño de espacios verdes', 8, '[\"reducir_papel\", \"reciclaje\"]', 'futuro', 5, 15, '[\"educacion_ambiental\", \"reduccion_contaminacion\"]', 6, 'si', 'quiza', 'Diseñar interiores sostenibles y promover plantas en espacios cerrados.', 'Promover jardines comunitarios.', 'Diseño ecológico y sostenible.', 'El diseño también puede contribuir al cuidado del medio ambiente.', '2024-11-13 02:01:32'),
(3, 'Jorge Valenzuela', 40, 'Agricultor', 'jorge.valenzuela@example.com', 'diariamente', 'Mantenimiento de cultivos, conservación de suelo', 10, '[\"evitar_quimicos\", \"plantacion\"]', 'si', 100, 200, '[\"conservacion_bosques\", \"desertificacion\"]', 10, 'tengo', 'no', 'Implementar sistemas agroforestales sostenibles.', 'Aumentar el acceso a recursos sostenibles para pequeños agricultores.', 'Gestión de recursos hídricos.', 'La agricultura sostenible es clave para un futuro equilibrado.', '2024-11-27 21:57:49'),
(4, 'Ana Beltrán', 22, 'Estudiante de Biología', 'ana.beltran@example.com', 'semanalmente', 'Estudios de biodiversidad, caminatas', 9, '[\"reducir_papel\", \"reciclaje\", \"plantacion\"]', 'si', 25, 50, '[\"proteccion_especies\", \"educacion_ambiental\"]', 8, 'si', 'si', 'Fomentar la reforestación en áreas urbanas.', 'Crear conciencia sobre la biodiversidad urbana.', 'Estudios sobre especies endémicas.', 'Es importante educar a las personas sobre su impacto en la biodiversidad.', '2024-11-27 21:59:25'),
(5, 'Juan Pérez', 28, 'Ingeniero Ambiental', 'juan.perez@example.com', 'semanalmente', 'Senderismo, fotografía', 8, '[\"reducir_papel\", \"reciclaje\", \"productos_ecologicos\"]', 'si', 15, 20, '[\"conservacion_bosques\", \"educacion_ambiental\"]', 7, 'si', 'si', 'Incrementar el reciclaje en mi hogar y comunidad.', 'Más áreas verdes y programas educativos sobre conservación.', 'Gestión de residuos y compostaje.', 'Me siento motivado por las acciones colectivas y quiero aprender más sobre conservación.', '2024-11-28 02:24:29'),
(6, 'María López', 35, 'Maestra', 'maria.lopez@example.com', 'ocasionalmente', 'Picnic, observación de aves', 6, '[\"plantacion\", \"evitar_quimicos\"]', 'futuro', 5, 10, '[\"proteccion_especies\", \"reduccion_contaminacion\"]', 5, 'si', 'quiza', 'Organizar actividades ambientales en la escuela.', 'Mayor conciencia sobre el reciclaje en mi comunidad.', 'Educación ambiental para niños y adolescentes.', 'Creo que cada pequeña acción cuenta y quiero inspirar a otros.', '2024-11-28 02:24:29'),
(7, 'Carlos Ruiz', 40, 'Agricultor', 'carlos.ruiz@example.com', 'diariamente', 'Trabajo agrícola, conservación de suelo', 10, '[\"reducir_papel\", \"plantacion\", \"evitar_quimicos\"]', 'no', 50, 100, '[\"conservacion_bosques\", \"desertificacion\"]', 9, 'tengo', 'no', 'Desarrollar técnicas más sostenibles en mis cultivos.', 'Promoción de prácticas agrícolas sostenibles.', 'Uso eficiente del agua y rotación de cultivos.', 'Estoy comprometido con la protección de mi entorno natural.', '2024-11-28 02:24:29'),
(8, 'Ana Martínez', 25, 'Estudiante', 'ana.martinez@example.com', 'mensualmente', 'Excursionismo, dibujo de paisajes', 7, '[\"reciclaje\", \"productos_ecologicos\"]', 'futuro', 2, 5, '[\"educacion_ambiental\", \"proteccion_especies\"]', 6, 'si', 'si', 'Participar en campañas de reciclaje en mi universidad.', 'Mejor infraestructura para el reciclaje.', 'Organización de eventos ecológicos.', 'Espero aprender más sobre cómo puedo contribuir directamente.', '2024-11-28 02:26:32'),
(9, 'Luis Gómez', 30, 'Diseñador Gráfico', 'luis.gomez@example.com', 'ocasionalmente', 'Fotografía, paseos en bicicleta', 5, '[\"reducir_papel\"]', 'no', 0, 0, '[\"reduccion_contaminacion\"]', 4, 'quiza', 'quiza', 'Reducir el uso de plásticos en mi vida diaria.', 'Conciencia sobre el impacto de la basura en áreas naturales.', 'Reducción de plástico y alternativas sostenibles.', 'Quiero ser más consciente de mi impacto ambiental.', '2024-11-28 02:26:32'),
(10, 'Carmen Sánchez', 45, 'Doctora', 'carmen.sanchez@example.com', 'semanalmente', 'Caminatas, observación de aves', 9, '[\"reciclaje\", \"plantacion\"]', 'si', 10, 30, '[\"proteccion_especies\", \"educacion_ambiental\"]', 8, 'si', 'si', 'Organizar talleres de educación ambiental para niños.', 'Incrementar las áreas verdes en los hospitales.', 'Educación ambiental y reforestación.', 'Creo que las pequeñas acciones tienen un gran impacto colectivo.', '2024-11-28 02:26:32'),
(11, 'Pedro López', 20, 'Estudiante', 'pedro.lopez@example.com', 'diariamente', 'Ciclismo, conservación del suelo', 10, '[\"reducir_papel\", \"reciclaje\", \"productos_ecologicos\"]', 'si', 8, 15, '[\"conservacion_bosques\", \"reduccion_contaminacion\"]', 9, 'tengo', 'si', 'Participar en brigadas ecológicas en mi comunidad.', 'Mayor protección a los parques locales.', 'Conservación del agua y la biodiversidad.', 'Estoy decidido a ser parte del cambio positivo.', '2024-11-28 02:26:32'),
(12, 'Rosa Fernández', 33, 'Chef', 'rosa.fernandez@example.com', 'mensualmente', 'Explorar nuevos lugares, recolección de frutos', 6, '[\"productos_ecologicos\", \"evitar_quimicos\"]', 'no', 3, 5, '[\"educacion_ambiental\", \"desertificacion\"]', 5, 'si', 'quiza', 'Usar ingredientes locales y sostenibles en mis recetas.', 'Acceso a más productos ecológicos en el mercado.', 'Cocina sostenible y huertos urbanos.', 'Quiero combinar mi pasión por la cocina con la sostenibilidad.', '2024-11-28 02:26:32'),
(13, 'Carlos Méndez', 29, 'Ingeniero', 'carlos.mendez@example.com', 'ocasionalmente', 'Caminatas, observación de fauna', 7, '[\"plantacion\"]', 'no', 4, 8, '[\"conservacion_bosques\", \"proteccion_especies\"]', 6, 'quiza', 'no', 'Unirme a una organización ambiental local.', 'Mejor gestión de residuos en mi comunidad.', 'Reforestación y educación ambiental.', 'Creo que juntos podemos hacer una gran diferencia.', '2024-11-28 02:26:32'),
(14, 'Laura Ruiz', 50, 'Abogada', 'laura.ruiz@example.com', 'semanalmente', 'Jardinería, fotografía de naturaleza', 8, '[\"evitar_quimicos\", \"plantacion\"]', 'si', 20, 40, '[\"educacion_ambiental\", \"reduccion_contaminacion\"]', 7, 'si', 'si', 'Promover políticas de sostenibilidad en mi oficina.', 'Más programas de educación ambiental.', 'Gestión de residuos y reciclaje.', 'Quiero liderar iniciativas sostenibles en mi entorno laboral.', '2024-11-28 02:26:32'),
(15, 'Jorge Vega', 37, 'Profesor', 'jorge.vega@example.com', 'diariamente', 'Caminatas con estudiantes', 10, '[\"reducir_papel\", \"reciclaje\", \"productos_ecologicos\"]', 'si', 30, 50, '[\"educacion_ambiental\", \"proteccion_especies\"]', 10, 'si', 'si', 'Incorporar educación ambiental en el currículo escolar.', 'Más programas para involucrar a los jóvenes en la conservación.', 'Educación y reforestación.', 'Me apasiona educar a las nuevas generaciones sobre sostenibilidad.', '2024-11-28 02:26:32'),
(16, 'Sofía Morales', 41, 'Artista', 'sofia.morales@example.com', 'ocasionalmente', 'Dibujo, recolección de materiales naturales', 6, '[\"reciclaje\"]', 'futuro', 0, 2, '[\"educacion_ambiental\", \"reduccion_contaminacion\"]', 4, 'si', 'quiza', 'Crear arte que inspire conciencia ambiental.', 'Más espacios para la educación ambiental.', 'Uso responsable de recursos naturales.', 'Quiero combinar mi arte con mensajes de sostenibilidad.', '2024-11-28 02:26:32'),
(17, 'Diego Herrera', 38, 'Comerciante', 'diego.herrera@example.com', 'mensualmente', 'Camping, pesca sostenible', 7, '[\"reducir_papel\", \"productos_ecologicos\"]', 'no', 5, 10, '[\"reduccion_contaminacion\", \"proteccion_especies\"]', 6, 'quiza', 'no', 'Adoptar prácticas sostenibles en mi negocio.', 'Más conciencia sobre la pesca responsable.', 'Gestión sostenible de recursos pesqueros.', 'Quiero ser un ejemplo para mis colegas y clientes.', '2024-11-28 02:26:32'),
(18, 'Elena Torres', 27, 'Psicóloga', 'elena.torres@example.com', 'semanalmente', 'Yoga, meditación al aire libre', 8, '[\"productos_ecologicos\", \"reciclaje\"]', 'si', 12, 25, '[\"educacion_ambiental\", \"conservacion_bosques\"]', 7, 'si', 'si', 'Promover espacios naturales para la salud mental.', 'Creación de parques comunitarios.', 'Técnicas de reforestación.', 'El contacto con la naturaleza mejora mi bienestar.', '2024-11-28 02:28:00'),
(19, 'Gabriel Ramírez', 33, 'Ingeniero Civil', 'gabriel.ramirez@example.com', 'ocasionalmente', 'Fotografía, observación de fauna', 6, '[\"reciclaje\"]', 'no', 5, 10, '[\"reduccion_contaminacion\"]', 5, 'quiza', 'quiza', 'Usar materiales sostenibles en proyectos de construcción.', 'Mejor manejo de desechos de construcción.', 'Sostenibilidad en infraestructuras urbanas.', 'Quiero liderar proyectos de construcción ecológica.', '2024-11-28 02:28:00'),
(20, 'Diana Gómez', 42, 'Contadora', 'diana.gomez@example.com', 'mensualmente', 'Excursionismo, fotografía', 7, '[\"reducir_papel\", \"reciclaje\"]', 'si', 4, 8, '[\"educacion_ambiental\", \"proteccion_especies\"]', 6, 'si', 'si', 'Implementar políticas de reciclaje en mi oficina.', 'Mayor acceso a recursos educativos ambientales.', 'Educación y reducción de desperdicios.', 'Creo que pequeños cambios generan grandes impactos.', '2024-11-28 02:28:00'),
(21, 'Héctor Méndez', 35, 'Electricista', 'hector.mendez@example.com', 'diariamente', 'Caminatas al aire libre', 9, '[\"reciclaje\", \"productos_ecologicos\"]', 'si', 10, 20, '[\"conservacion_bosques\", \"reduccion_contaminacion\"]', 8, 'si', 'si', 'Instalar sistemas de energía renovable.', 'Uso de energías limpias en la comunidad.', 'Paneles solares y eficiencia energética.', 'Me gustaría aprender más sobre energías renovables.', '2024-11-28 02:28:00'),
(22, 'Natalia Rivera', 30, 'Doctora', 'natalia.rivera@example.com', 'semanalmente', 'Jardinería, meditación', 8, '[\"evitar_quimicos\", \"plantacion\"]', 'si', 15, 30, '[\"proteccion_especies\", \"educacion_ambiental\"]', 9, 'si', 'si', 'Organizar campañas médicas en áreas rurales.', 'Conciencia sobre la salud y la naturaleza.', 'Conexión entre salud y sostenibilidad.', 'Me inspira la relación entre naturaleza y bienestar.', '2024-11-28 02:28:00'),
(23, 'Javier Ortega', 50, 'Carpintero', 'javier.ortega@example.com', 'mensualmente', 'Senderismo, construcción ecológica', 7, '[\"productos_ecologicos\"]', 'no', 3, 5, '[\"reduccion_contaminacion\", \"educacion_ambiental\"]', 6, 'si', 'quiza', 'Construir muebles con materiales reciclados.', 'Acceso a recursos reciclados para mi trabajo.', 'Sostenibilidad en la carpintería.', 'Quiero liderar un cambio en mi industria.', '2024-11-28 02:28:00'),
(24, 'Sara Ramírez', 40, 'Profesora', 'sara.ramirez@example.com', 'ocasionalmente', 'Lectura, observación de naturaleza', 6, '[\"reducir_papel\", \"reciclaje\"]', 'futuro', 0, 0, '[\"educacion_ambiental\"]', 5, 'si', 'quiza', 'Incluir temas ambientales en mis clases.', 'Más material educativo sobre sostenibilidad.', 'Educación ambiental para jóvenes.', 'Quiero ser una guía para la próxima generación.', '2024-11-28 02:28:00'),
(25, 'Pablo Fernández', 29, 'Programador', 'pablo.fernandez@example.com', 'ocasionalmente', 'Ciclismo, fotografía', 5, '[\"reciclaje\"]', 'no', 2, 4, '[\"reduccion_contaminacion\"]', 4, 'quiza', 'no', 'Desarrollar apps para educación ambiental.', 'Mayor interés en tecnología y sostenibilidad.', 'Tecnología para el medio ambiente.', 'Quiero usar mis habilidades para el cambio.', '2024-11-28 02:28:00'),
(26, 'Carla López', 36, 'Periodista', 'carla.lopez@example.com', 'mensualmente', 'Escribir, documentales de naturaleza', 7, '[\"reciclaje\", \"productos_ecologicos\"]', 'futuro', 0, 0, '[\"educacion_ambiental\", \"conservacion_bosques\"]', 6, 'si', 'si', 'Crear contenido educativo sobre ecología.', 'Más información pública sobre sostenibilidad.', 'Comunicación y divulgación ambiental.', 'Creo en el poder de las historias para inspirar.', '2024-11-28 02:28:00'),
(27, 'Fernando Vargas', 45, 'Empresario', 'fernando.vargas@example.com', 'semanalmente', 'Negocios sostenibles', 8, '[\"reducir_papel\", \"reciclaje\"]', 'si', 20, 50, '[\"educacion_ambiental\", \"desertificacion\"]', 8, 'tengo', 'si', 'Incorporar políticas sostenibles en mi empresa.', 'Más apoyo para negocios verdes.', 'Sostenibilidad en los negocios.', 'Quiero ser un ejemplo de éxito responsable.', '2024-11-28 02:28:00'),
(28, 'Lucía Navarro', 23, 'Estudiante', 'lucia.navarro@example.com', 'diariamente', 'Senderismo, limpieza de ríos', 10, '[\"reducir_papel\", \"reciclaje\", \"productos_ecologicos\"]', 'si', 18, 40, '[\"reduccion_contaminacion\", \"proteccion_especies\"]', 9, 'si', 'si', 'Participar en más limpiezas comunitarias.', 'Mayor educación ambiental en mi ciudad.', 'Restauración de ecosistemas locales.', 'Creo que todos podemos contribuir.', '2024-11-28 02:28:00'),
(29, 'Esteban Cruz', 39, 'Técnico', 'esteban.cruz@example.com', 'ocasionalmente', 'Fotografía, jardinería', 5, '[\"evitar_quimicos\"]', 'no', 1, 2, '[\"educacion_ambiental\"]', 4, 'quiza', 'quiza', 'Reducir el uso de químicos en mi jardín.', 'Mayor acceso a productos ecológicos.', 'Jardinería sostenible.', 'Quiero aprender más sobre compostaje.', '2024-11-28 02:28:00'),
(30, 'Marta Silva', 47, 'Médica Veterinaria', 'marta.silva@example.com', 'semanalmente', 'Cuidado de animales', 9, '[\"productos_ecologicos\"]', 'si', 10, 25, '[\"proteccion_especies\"]', 8, 'si', 'si', 'Proteger a animales en peligro de extinción.', 'Más áreas protegidas.', 'Conservación de fauna.', 'Creo que los animales son esenciales para el equilibrio natural.', '2024-11-28 02:28:00');

--
ALTER TABLE `form_info`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=31;
COMMIT;
